/**
 * Seed data for the Threads (garments) marketplace. In production, replace
 * with a fetch from your backend or Firestore collection.
 */
import type { Garment } from "@/types/garment";

/** Example garments for the Threads tab. */
export const GARMENTS: Garment[] = [
  {
    id: "gar_classic_white",
    name: "Classic White Tee",
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "White",
    sku: "TEE-CLS-WHT-001",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["tees", "bestseller"],
    image: "https://picsum.photos/seed/tee1/400/400",
    description: "Essential crewneck tee, soft cotton.",
    price: "$24.99",
    active: true,
  },
  {
    id: "gar_black_hoodie",
    name: "Black Hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Black",
    sku: "HOD-BLK-001",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["hoodies", "bestseller"],
    image: "https://picsum.photos/seed/tee2/400/400",
    description: "Heavyweight fleece hoodie.",
    price: "$49.99",
    active: true,
  },
  {
    id: "gar_navy_crew",
    name: "Navy Crewneck",
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Navy",
    sku: "TEE-NVY-002",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["tees", "new"],
    image: "https://picsum.photos/seed/tee3/400/400",
    description: "Classic navy crewneck.",
    price: "$26.99",
    active: true,
  },
  {
    id: "gar_grey_oversized",
    name: "Grey Oversized",
    sizes: ["S", "M", "L", "XL"],
    color: "Heather Grey",
    sku: "TEE-GRY-OVR-003",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["tees", "bestseller", "new"],
    image: "https://picsum.photos/seed/tee4/400/400",
    description: "Oversized unisex tee.",
    price: "$32.99",
    active: true,
  },
  {
    id: "gar_olive_tee",
    name: "Olive Graphic Tee",
    sizes: ["XS", "S", "M", "L"],
    color: "Olive",
    sku: "TEE-OLV-004",
    author: "Threads Basics",
    releaseYear: 2023,
    categories: ["tees", "limited-edition"],
    image: "https://picsum.photos/seed/tee5/400/400",
    description: "Olive green tee, relaxed fit.",
    price: "$28.99",
    active: true,
  },
  {
    id: "gar_sand_tee",
    name: "Sand Cotton Tee",
    sizes: ["S", "M", "L", "XL"],
    color: "Sand",
    sku: "TEE-SND-005",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["tees", "new"],
    image: "https://picsum.photos/seed/tee6/400/400",
    description: "Soft sand-colored cotton.",
    price: "$25.99",
    active: true,
  },
  {
    id: "gar_burgundy_hoodie",
    name: "Burgundy Hoodie",
    sizes: ["M", "L", "XL", "XXL"],
    color: "Burgundy",
    sku: "HOD-BUR-002",
    author: "Threads Basics",
    releaseYear: 2023,
    categories: ["hoodies", "limited-edition"],
    image: "https://picsum.photos/seed/tee7/400/400",
    description: "Rich burgundy fleece.",
    price: "$54.99",
    active: true,
  },
  {
    id: "gar_white_crop",
    name: "White Crop Tee",
    sizes: ["XS", "S", "M"],
    color: "White",
    sku: "TEE-CRP-WHT-006",
    author: "Threads Basics",
    releaseYear: 2024,
    categories: ["tees", "new"],
    image: "https://picsum.photos/seed/tee8/400/400",
    description: "Cropped fit, high cotton content.",
    price: "$22.99",
    active: true,
  },
];
